import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";

import Header from "./layout/Header";
import { MainContainer } from "./layout/MainContainer";
import ThemeProvider from "./theme/themeProvider";

import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.variable}>
        <ThemeProvider>
          <MainContainer>
            <Header />
            {children}
          </MainContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}