import type { Metadata } from 'next';
import localFont from 'next/font/local';

import Header from './layout/Header';
import Footer from './layout/Footer';
import { LayoutContainer } from './layout/LayoutContainer';
import ThemeProvider from './theme/themeProvider';

import './globals.css';

const ubuntu = localFont({
  src: [
    {
      path: '../public/fonts/Ubuntu-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Ubuntu-Medium.ttf',
      weight: '500',
      style: 'Medium',
    },
    {
      path: '../public/fonts/Ubuntu-Bold.ttf',
      weight: '700',
      style: 'Bold',
    }
  ],
  variable: '--font-ubuntu',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${ubuntu.className}`}>
        <ThemeProvider>
          <LayoutContainer>
            <Header />
            <div className="page-container">
              <main className="main-content">{children}</main>
              <Footer />
            </div>
          </LayoutContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
